package com.os4.musiccover;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;

/**
 * Pure Java Dual-Track MP4 Injector.
 * Takes a single-stream video MP4 (generated by Android's native MediaCodec + MediaMuxer)
 * and interleaves a 5-byte GoPro MET (gpmd) null-depth mask stream as Track 0.
 *
 * Uses precise MP4 box-tree traversal to locate boxes, supporting both stco and co64,
 * and arbitrary box orderings.
 */
public class FastMp4Muxer {

    private static final String TAG = "[MCDualMux] ";

    // 5-byte FastPlayer "empty/null mask" indicator (transparent foreground)
    private static final byte[] GPMD_NULL_MASK = new byte[] {
            (byte) 0x80, (byte) 0xb1, 0x71, (byte) 0x80, 0x00
    };

    // Base64 template of Track 0 (gpmd track) from Xiaomi's depth video (490 bytes)
    private static final String TRAK0_BASE64 =
            "AAAB6nRyYWsAAABcdGtoZAAAAAIAAAAAAAAAAAAAAAEAAAAAAAAAIgAAAAAAAAAAAAAAAgAAAAAAAQAA"
            + "AAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAACRlZHRzAAAAHGVsc3QAAAAA"
            + "AAAAAQAAACIAAAAAAAEAAAAAAWJtZGlhAAAAIG1kaGQAAAAAAAAAAAAAAAAAAV+QAAALuFXEAAAAAAAq"
            + "aGRscgAAAAAAAAAAbWV0YQAAAAAAAAAAAAAAAEdvUHJvIE1FVAAAAAEQbWluZgAAAFhnbWhkAAAAGGdt"
            + "aW4AAAAAAECAAIAAgAAAAAAAAAAALHRleHQAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAA"
            + "AAAAAAAMZ3BtZAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAACMc3RibAAA"
            + "ACRzdHNkAAAAAAAAAAEAAAAUZ3BtZAAAAAAAAAABAAAAAAAAABhzdHRzAAAAAAAAAAEAAAACAAAF3AAA"
            + "ABxzdHNjAAAAAAAAAAEAAAABAAAAAQAAAAEAAAAUc3RzegAAAAAAAAAFAAAAAgAAABhzdGNvAAAAAAAA"
            + "AAIAAAAsAAEQXA==";

    private static class Box {
        final String type;
        final int offset;
        final int size;

        Box(String type, int offset, int size) {
            this.type = type;
            this.offset = offset;
            this.size = size;
        }
    }

    private static List<Box> parseBoxes(byte[] data, int start, int end) {
        List<Box> list = new ArrayList<>();
        int pos = start;
        ByteBuffer buf = ByteBuffer.wrap(data).order(ByteOrder.BIG_ENDIAN);
        while (pos + 8 <= end) {
            int sz = buf.getInt(pos);
            String type = new String(data, pos + 4, 4, StandardCharsets.ISO_8859_1);
            long boxSz = (sz == 1 && pos + 16 <= end) ? buf.getLong(pos + 8) : (sz & 0xFFFFFFFFL);
            if (boxSz <= 0 || pos + boxSz > end) {
                boxSz = end - pos;
            }
            list.add(new Box(type, pos, (int) boxSz));
            pos += (int) boxSz;
        }
        return list;
    }

    private static Box findBox(List<Box> boxes, String type) {
        for (Box b : boxes) {
            if (b.type.equals(type)) return b;
        }
        return null;
    }

    /** The gpmd sample period the OEM's own template carries, kept as it is. */
    private static final int GPMD_SAMPLE_DELTA = 1500;

    /**
     * The OEM's gpmd track, at the right sample count.
     *
     * The template is Xiaomi's own depth track with a two-sample table in it, and the parts of it
     * that depend on how long the picture is are the parts rebuilt here: stsz's count, stts's one
     * run, and stco's offsets - one gpmd sample interleaved in front of each video sample, which
     * is the pairing the template was written for.
     *
     * Everything else is the OEM's and is left exactly as it is: the timescale, the durations
     * (which were never tied to the picture anyway - its own file pairs a 33ms gpmd track with a
     * 100ms video and works), the GoPro MET sample entry, the edit list. Only count-dependent
     * boxes are touched, and mdhd's duration is kept equal to the stts total so the two do not
     * disagree about a track that got longer.
     *
     * At two samples this reproduces the old in-place patch byte for byte, which is the shape
     * every cover video had before the fade existed - that is what the offline check compares.
     *
     * @return the rebuilt trak, or null if the template is not the shape this expects
     */
    private static byte[] rebuildGpmdTrak(byte[] trak0, int[] absOffsets) {
        Box mdia = findBox(parseBoxes(trak0, 8, trak0.length), "mdia");
        if (mdia == null) return null;
        Box minf = findBox(parseBoxes(trak0, mdia.offset + 8, mdia.offset + mdia.size), "minf");
        if (minf == null) return null;
        Box stbl = findBox(parseBoxes(trak0, minf.offset + 8, minf.offset + minf.size), "stbl");
        if (stbl == null) return null;
        List<Box> stblBoxes = parseBoxes(trak0, stbl.offset + 8, stbl.offset + stbl.size);
        Box stts = findBox(stblBoxes, "stts");
        Box stsz = findBox(stblBoxes, "stsz");
        Box stco = findBox(stblBoxes, "stco");
        if (stts == null || stsz == null || stco == null) return null;

        int n = absOffsets.length;
        ByteBuffer src = ByteBuffer.wrap(trak0).order(ByteOrder.BIG_ENDIAN);

        byte[] newStts = new byte[24];
        ByteBuffer.wrap(newStts).order(ByteOrder.BIG_ENDIAN)
                .putInt(24).put("stts".getBytes(StandardCharsets.ISO_8859_1))
                .putInt(0).putInt(1)
                .putInt(n).putInt(GPMD_SAMPLE_DELTA);

        // The template states the mask's size once (sample_size = 5), so only the count moves.
        byte[] newStsz = new byte[20];
        ByteBuffer.wrap(newStsz).order(ByteOrder.BIG_ENDIAN)
                .putInt(20).put("stsz".getBytes(StandardCharsets.ISO_8859_1))
                .putInt(0).putInt(GPMD_NULL_MASK.length).putInt(n);

        byte[] newStco = new byte[16 + 4 * n];
        ByteBuffer stcoBuf = ByteBuffer.wrap(newStco).order(ByteOrder.BIG_ENDIAN);
        stcoBuf.putInt(newStco.length).put("stco".getBytes(StandardCharsets.ISO_8859_1))
                .putInt(0).putInt(n);
        for (int i = 0; i < n; i++) stcoBuf.putInt(absOffsets[i]);

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        out.write(trak0, 0, stts.offset);
        out.write(newStts, 0, newStts.length);
        out.write(trak0, stts.offset + stts.size, stsz.offset - (stts.offset + stts.size));
        out.write(newStsz, 0, newStsz.length);
        out.write(trak0, stsz.offset + stsz.size, stco.offset - (stsz.offset + stsz.size));
        out.write(newStco, 0, newStco.length);
        out.write(trak0, stco.offset + stco.size, trak0.length - (stco.offset + stco.size));
        byte[] built = out.toByteArray();

        int delta = built.length - trak0.length;
        ByteBuffer dst = ByteBuffer.wrap(built).order(ByteOrder.BIG_ENDIAN);
        dst.putInt(0, built.length);
        dst.putInt(stbl.offset, src.getInt(stbl.offset) + delta);
        dst.putInt(minf.offset, src.getInt(minf.offset) + delta);
        dst.putInt(mdia.offset, src.getInt(mdia.offset) + delta);

        Box mdhd = findBox(parseBoxes(trak0, mdia.offset + 8, mdia.offset + mdia.size), "mdhd");
        if (mdhd != null && (trak0[mdhd.offset + 8] & 0xFF) == 0) {
            dst.putInt(mdhd.offset + 24, n * GPMD_SAMPLE_DELTA);
        }
        return built;
    }

    /**
     * Converts a single-track video MP4 file into a dual-track (gpmd + video) MP4 file.
     *
     * @param singleTrackFile The source MP4 file produced by MediaMuxer
     * @param destFile        The target dual-track MP4 file for FastPlayer
     * @return true if successful, false otherwise
     */
    public static boolean injectGpmdTrack(File singleTrackFile, File destFile) {
        if (singleTrackFile == null || !singleTrackFile.exists() || singleTrackFile.length() < 64) {
            Xp.log(TAG + "singleTrackFile invalid: " + singleTrackFile);
            return false;
        }

        try {
            int fileLen = (int) singleTrackFile.length();
            byte[] single = new byte[fileLen];
            try (FileInputStream fis = new FileInputStream(singleTrackFile)) {
                int read = 0;
                while (read < fileLen) {
                    int r = fis.read(single, read, fileLen - read);
                    if (r < 0) break;
                    read += r;
                }
            }

            ByteBuffer buf = ByteBuffer.wrap(single).order(ByteOrder.BIG_ENDIAN);

            // Locate top-level boxes
            List<Box> top = parseBoxes(single, 0, fileLen);
            Box ftyp = findBox(top, "ftyp");
            Box mdat = findBox(top, "mdat");
            Box moov = findBox(top, "moov");
            if (ftyp == null || mdat == null || moov == null) {
                Xp.log(TAG + "missing essential top-level box (ftyp/mdat/moov)");
                return false;
            }

            // In moov: mvhd, trak
            List<Box> moovBoxes = parseBoxes(single, moov.offset + 8, moov.offset + moov.size);
            Box mvhd = findBox(moovBoxes, "mvhd");
            Box trak = findBox(moovBoxes, "trak");
            if (mvhd == null || trak == null) {
                Xp.log(TAG + "missing mvhd or trak in moov");
                return false;
            }

            // In trak: tkhd, mdia -> minf -> stbl
            List<Box> trakBoxes = parseBoxes(single, trak.offset + 8, trak.offset + trak.size);
            Box tkhd = findBox(trakBoxes, "tkhd");
            Box mdia = findBox(trakBoxes, "mdia");
            if (tkhd == null || mdia == null) {
                Xp.log(TAG + "missing tkhd or mdia in trak");
                return false;
            }

            List<Box> mdiaBoxes = parseBoxes(single, mdia.offset + 8, mdia.offset + mdia.size);
            Box minf = findBox(mdiaBoxes, "minf");
            if (minf == null) {
                Xp.log(TAG + "missing minf in mdia");
                return false;
            }

            List<Box> minfBoxes = parseBoxes(single, minf.offset + 8, minf.offset + minf.size);
            Box stbl = findBox(minfBoxes, "stbl");
            if (stbl == null) {
                Xp.log(TAG + "missing stbl in minf");
                return false;
            }

            List<Box> stblBoxes = parseBoxes(single, stbl.offset + 8, stbl.offset + stbl.size);
            Box stsc = findBox(stblBoxes, "stsc");
            Box stco = findBox(stblBoxes, "stco");
            Box co64 = findBox(stblBoxes, "co64");
            Box stsz = findBox(stblBoxes, "stsz");
            Box chunkBox = (stco != null) ? stco : co64;

            if (stsc == null || chunkBox == null || stsz == null) {
                Xp.log(TAG + "missing stsc, chunk offset (stco/co64), or stsz in stbl");
                return false;
            }

            // Read the sample table as a table, not as "the first two samples".
            //
            // This used to read sample 0 and 1 and interleave exactly those, which was the shape
            // of the cover video until it had a fade in it: two identical frames and no third.
            // A fade needs more samples than that, so the offsets are expanded here from stsc
            // and the chunk offsets - the spec's own table, which is what makes this independent
            // of how MediaMuxer chose to pack the samples into chunks - and the sizes come from
            // stsz. Anything the table does not cover is refused rather than mis-muxed, because
            // a wrong offset is a file the player opens and renders as garbage.
            int fixedSampleSize = buf.getInt(stsz.offset + 12);
            int sampleCount = buf.getInt(stsz.offset + 16);
            if (sampleCount < 1) {
                Xp.log(TAG + "no samples found in stsz");
                return false;
            }
            int[] sampleSizes = new int[sampleCount];
            for (int i = 0; i < sampleCount; i++) {
                sampleSizes[i] = fixedSampleSize != 0
                        ? fixedSampleSize
                        : buf.getInt(stsz.offset + 20 + 4 * i);
            }

            int chunkCount = buf.getInt(chunkBox.offset + 12);
            int stscEntries = buf.getInt(stsc.offset + 12);
            if (chunkCount < 1 || stscEntries < 1) {
                Xp.log(TAG + "refusing: " + chunkCount + " chunks, " + stscEntries + " stsc entries");
                return false;
            }
            int[] stscFirst = new int[stscEntries];
            int[] stscPerChunk = new int[stscEntries];
            for (int e = 0; e < stscEntries; e++) {
                int base = stsc.offset + 16 + 12 * e;
                stscFirst[e] = buf.getInt(base);
                stscPerChunk[e] = buf.getInt(base + 4);
                if (stscPerChunk[e] < 1) {
                    Xp.log(TAG + "refusing: stsc entry " + e + " says " + stscPerChunk[e]
                            + " samples per chunk");
                    return false;
                }
            }

            long[] srcOffsets = new long[sampleCount];
            int sample = 0;
            for (int c = 0; c < chunkCount && sample < sampleCount; c++) {
                int perChunk = stscPerChunk[0];
                for (int e = stscEntries - 1; e >= 0; e--) {
                    if (c + 1 >= stscFirst[e]) {
                        perChunk = stscPerChunk[e];
                        break;
                    }
                }
                long offset = chunkBox.type.equals("co64")
                        ? buf.getLong(chunkBox.offset + 16 + 8 * c)
                        : (buf.getInt(chunkBox.offset + 16 + 4 * c) & 0xFFFFFFFFL);
                for (int k = 0; k < perChunk && sample < sampleCount; k++) {
                    srcOffsets[sample] = offset;
                    offset += sampleSizes[sample];
                    sample++;
                }
            }
            if (sample != sampleCount) {
                Xp.log(TAG + "refusing: the sample table covers " + sample + " of " + sampleCount
                        + " samples");
                return false;
            }
            for (int i = 0; i < sampleCount; i++) {
                if (srcOffsets[i] + sampleSizes[i] > fileLen) {
                    Xp.log(TAG + "sample " + i + " runs past the end of the file");
                    return false;
                }
            }

            // 1. Build new mdat payload: interleave gpmd with the video frames.
            //
            // Absolute offsets as they are built, because they are what both tracks' stco end up
            // holding: ftyp comes first, and every sample sits 8 bytes into its mdat box.
            int absMdatStart = ftyp.size;
            ByteArrayOutputStream newMdatStream = new ByteArrayOutputStream();
            int[] absGpmdOffsets = new int[sampleCount];
            int[] absVideoOffsets = new int[sampleCount];
            for (int i = 0; i < sampleCount; i++) {
                absGpmdOffsets[i] = absMdatStart + newMdatStream.size() + 8;
                newMdatStream.write(GPMD_NULL_MASK);
                absVideoOffsets[i] = absMdatStart + newMdatStream.size() + 8;
                newMdatStream.write(single, (int) srcOffsets[i], sampleSizes[i]);
            }

            byte[] newMdatPayload = newMdatStream.toByteArray();
            byte[] newMdatHeader = new byte[8];
            ByteBuffer.wrap(newMdatHeader).order(ByteOrder.BIG_ENDIAN)
                    .putInt(newMdatPayload.length + 8)
                    .put("mdat".getBytes(StandardCharsets.ISO_8859_1));

            // 2. Track 0, rebuilt for this many samples. Its counts are the only part of the
            //    OEM's template that depends on the length of the picture, so they are the only
            //    part that is rewritten - see rebuildGpmdTrak().
            byte[] trak0 = Base64.getDecoder().decode(TRAK0_BASE64);
            byte[] newTrak0 = rebuildGpmdTrak(trak0, absGpmdOffsets);
            if (newTrak0 == null) {
                Xp.log(TAG + "cannot rebuild the gpmd track for " + sampleCount + " samples");
                return false;
            }

            // 3. Prepare trak1 (video) from single
            byte[] trakData = new byte[trak.size];
            System.arraycopy(single, trak.offset, trakData, 0, trak.size);
            int trakRelOffset = trak.offset;

            // Update track_id to 2 in tkhd
            int relTkhd = tkhd.offset - trakRelOffset;
            ByteBuffer.wrap(trakData).order(ByteOrder.BIG_ENDIAN).putInt(relTkhd + 20, 2);

            // Rebuild stsc: 1 entry (first_chunk=1, samples_per_chunk=1, desc_idx=1)
            byte[] newStsc = new byte[28];
            ByteBuffer.wrap(newStsc).order(ByteOrder.BIG_ENDIAN)
                    .putInt(28).put("stsc".getBytes(StandardCharsets.ISO_8859_1))
                    .putInt(0).putInt(1)
                    .putInt(1).putInt(1).putInt(1);

            // Rebuild stco: one entry per sample
            byte[] newStco = new byte[16 + 4 * sampleCount];
            ByteBuffer newStcoBuf = ByteBuffer.wrap(newStco).order(ByteOrder.BIG_ENDIAN);
            newStcoBuf.putInt(newStco.length).put("stco".getBytes(StandardCharsets.ISO_8859_1))
                    .putInt(0).putInt(sampleCount);
            for (int i = 0; i < sampleCount; i++) {
                newStcoBuf.putInt(absVideoOffsets[i]);
            }

            // Replace stsc and chunkBox in trakData
            int relStsc = stsc.offset - trakRelOffset;
            int relChunk = chunkBox.offset - trakRelOffset;

            ByteArrayOutputStream assembledTrak = new ByteArrayOutputStream();
            assembledTrak.write(trakData, 0, relStsc);
            assembledTrak.write(newStsc);
            assembledTrak.write(trakData, relStsc + stsc.size, relChunk - (relStsc + stsc.size));
            assembledTrak.write(newStco);
            assembledTrak.write(trakData, relChunk + chunkBox.size, trakData.length - (relChunk + chunkBox.size));
            byte[] newTrak1 = assembledTrak.toByteArray();
            ByteBuffer newTrak1Buf = ByteBuffer.wrap(newTrak1).order(ByteOrder.BIG_ENDIAN);

            // Size delta for trak1 and containers
            int sizeDelta = (newStsc.length - stsc.size) + (newStco.length - chunkBox.size);

            int relStbl = stbl.offset - trakRelOffset;
            int relMinf = minf.offset - trakRelOffset;
            int relMdia = mdia.offset - trakRelOffset;

            newTrak1Buf.putInt(relStbl, newTrak1Buf.getInt(relStbl) + sizeDelta);
            newTrak1Buf.putInt(relMinf, newTrak1Buf.getInt(relMinf) + sizeDelta);
            newTrak1Buf.putInt(relMdia, newTrak1Buf.getInt(relMdia) + sizeDelta);
            newTrak1Buf.putInt(0, newTrak1.length);

            // 4. Update mvhd next_track_id to 3
            byte[] mvhdData = new byte[mvhd.size];
            System.arraycopy(single, mvhd.offset, mvhdData, 0, mvhd.size);
            int mvhdVer = mvhdData[8] & 0xFF;
            int nextTrackOffset = (mvhdVer == 1) ? 116 : 104;
            ByteBuffer.wrap(mvhdData).order(ByteOrder.BIG_ENDIAN).putInt(nextTrackOffset, 3);

            // 5. Assemble moov
            ByteArrayOutputStream moovStream = new ByteArrayOutputStream();
            moovStream.write(mvhdData);
            moovStream.write(newTrak0);
            moovStream.write(newTrak1);
            byte[] newMoovPayload = moovStream.toByteArray();

            byte[] newMoovHeader = new byte[8];
            ByteBuffer.wrap(newMoovHeader).order(ByteOrder.BIG_ENDIAN)
                    .putInt(newMoovPayload.length + 8)
                    .put("moov".getBytes(StandardCharsets.ISO_8859_1));

            // 6. Write final MP4: [ftyp][new mdat][new moov]
            byte[] ftypData = new byte[ftyp.size];
            System.arraycopy(single, ftyp.offset, ftypData, 0, ftyp.size);

            File tempDest = new File(destFile.getAbsolutePath() + ".tmp");
            try (FileOutputStream fos = new FileOutputStream(tempDest)) {
                fos.write(ftypData);
                fos.write(newMdatHeader);
                fos.write(newMdatPayload);
                fos.write(newMoovHeader);
                fos.write(newMoovPayload);
            }

            if (destFile.exists()) {
                destFile.delete();
            }
            boolean renamed = tempDest.renameTo(destFile);
            Xp.log(TAG + "injectGpmdTrack succeeded: " + destFile.getAbsolutePath()
                    + " (" + destFile.length() + "B, delta=" + sizeDelta + ")");
            return renamed;

        } catch (Throwable t) {
            Xp.log(TAG + "injectGpmdTrack failed: " + t);
            return false;
        }
    }
}
