package com.os4.musiccover;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.Base64;

/**
 * Pure Java Dual-Track MP4 Injector.
 * Takes a single-stream video MP4 (generated by Android's native MediaCodec + MediaMuxer)
 * and interleaves a 5-byte GoPro MET (gpmd) null-depth mask stream as Track 0.
 *
 * This produces a 100% compliant dual-track MP4 (Stream 0: gpmd, Stream 1: video)
 * that satisfies HyperOS's FastPlayer dual-stream demuxer natively without any
 * native memory patching or NDK dependencies.
 */
public class FastMp4Muxer {

    private static final String TAG = "[MCDualMux] ";

    // 5-byte FastPlayer "empty/null mask" indicator (transparent foreground)
    private static final byte[] GPMD_NULL_MASK = new byte[] {
            (byte) 0x80, (byte) 0xb1, 0x71, (byte) 0x80, 0x00
    };

    // Base64 template of Track 0 (gpmd track) from Xiaomi's depth video (490 bytes)
    private static final String TRAK0_BASE64 =
            "AAAB6nRyYWsAAABcdGtoZAAAAAIAAAAAAAAAAAAAAAEAAAAAAAAAIgAAAAAAAAAAAAAAAgAAAAAAAQAA"
            + "AAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAACRlZHRzAAAAHGVsc3QAAAAA"
            + "AAAAAQAAACIAAAAAAAEAAAAAAWJtZGlhAAAAIG1kaGQAAAAAAAAAAAAAAAAAAV+QAAALuFXEAAAAAAAq"
            + "aGRscgAAAAAAAAAAbWV0YQAAAAAAAAAAAAAAAEdvUHJvIE1FVAAAAAEQbWluZgAAAFhnbWhkAAAAGGdt"
            + "aW4AAAAAAECAAIAAgAAAAAAAAAAALHRleHQAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAA"
            + "AAAAAAAMZ3BtZAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAACMc3RibAAA"
            + "ACRzdHNkAAAAAAAAAAEAAAAUZ3BtZAAAAAAAAAABAAAAAAAAABhzdHRzAAAAAAAAAAEAAAACAAAF3AAA"
            + "ABxzdHNjAAAAAAAAAAEAAAABAAAAAQAAAAEAAAAUc3RzegAAAAAAAAAFAAAAAgAAABhzdGNvAAAAAAAA"
            + "AAIAAAAsAAEQXA==";

    /**
     * Converts a single-track video MP4 file into a dual-track (gpmd + video) MP4 file.
     *
     * @param singleTrackFile The source MP4 file produced by MediaMuxer
     * @param destFile        The target dual-track MP4 file for FastPlayer
     * @return true if successful, false otherwise
     */
    public static boolean injectGpmdTrack(File singleTrackFile, File destFile) {
        if (singleTrackFile == null || !singleTrackFile.exists() || singleTrackFile.length() < 64) {
            Xp.log(TAG + "singleTrackFile invalid: " + singleTrackFile);
            return false;
        }

        try {
            int fileLen = (int) singleTrackFile.length();
            byte[] single = new byte[fileLen];
            try (FileInputStream fis = new FileInputStream(singleTrackFile)) {
                int read = 0;
                while (read < fileLen) {
                    int r = fis.read(single, read, fileLen - read);
                    if (r < 0) break;
                    read += r;
                }
            }

            ByteBuffer buf = ByteBuffer.wrap(single).order(ByteOrder.BIG_ENDIAN);

            // Locate top-level boxes: ftyp, mdat, moov
            int mdatIdx = findBox(single, "mdat");
            int moovIdx = findBox(single, "moov");
            if (mdatIdx < 0 || moovIdx < 0) {
                Xp.log(TAG + "mdat or moov box not found");
                return false;
            }

            int mdatSz = buf.getInt(mdatIdx);
            int moovSz = buf.getInt(moovIdx);

            // Find stsz in single to get video sample sizes
            int stszIdx = findBox(single, "stsz");
            if (stszIdx < 0) {
                Xp.log(TAG + "stsz not found in single video track");
                return false;
            }

            int sampleCount = buf.getInt(stszIdx + 16);
            if (sampleCount < 1) {
                Xp.log(TAG + "no samples found in stsz");
                return false;
            }

            int sample0Sz = buf.getInt(stszIdx + 20);
            int sample1Sz = (sampleCount > 1) ? buf.getInt(stszIdx + 24) : 0;

            // Raw video samples from mdat
            int mdatPayloadStart = mdatIdx + 8;
            byte[] rawS0 = new byte[sample0Sz];
            System.arraycopy(single, mdatPayloadStart, rawS0, 0, sample0Sz);

            byte[] rawS1 = null;
            if (sample1Sz > 0) {
                rawS1 = new byte[sample1Sz];
                System.arraycopy(single, mdatPayloadStart + sample0Sz, rawS1, 0, sample1Sz);
            }

            // 1. Interleave gpmd (5 bytes) with video frames in new mdat
            // Offsets are dynamically calculated relative to mdat payload start
            int mdatPayloadOffset = mdatIdx + 8;
            int offGpmd0 = mdatPayloadOffset;
            int offVideo0 = offGpmd0 + GPMD_NULL_MASK.length;
            int offGpmd1 = offVideo0 + sample0Sz;
            int offVideo1 = offGpmd1 + GPMD_NULL_MASK.length;

            ByteArrayOutputStream newMdatStream = new ByteArrayOutputStream();
            newMdatStream.write(GPMD_NULL_MASK);
            newMdatStream.write(rawS0);
            if (rawS1 != null) {
                newMdatStream.write(GPMD_NULL_MASK);
                newMdatStream.write(rawS1);
            }
            byte[] newMdatPayload = newMdatStream.toByteArray();

            byte[] newMdatHeader = new byte[8];
            ByteBuffer.wrap(newMdatHeader).order(ByteOrder.BIG_ENDIAN)
                    .putInt(newMdatPayload.length + 8)
                    .put("mdat".getBytes());

            // 2. Prepare trak0 from Base64 template
            byte[] trak0 = Base64.getDecoder().decode(TRAK0_BASE64);
            ByteBuffer trak0Buf = ByteBuffer.wrap(trak0).order(ByteOrder.BIG_ENDIAN);
            int stcoTrak0 = findSubBox(trak0, "stco");
            if (stcoTrak0 < 0) {
                Xp.log(TAG + "stco not found in trak0 template");
                return false;
            }
            trak0Buf.putInt(stcoTrak0 + 16, offGpmd0);
            trak0Buf.putInt(stcoTrak0 + 20, (rawS1 != null) ? offGpmd1 : offGpmd0);

            // 3. Prepare trak1 (video) from single
            int t1Idx = findBox(single, "trak");
            if (t1Idx < 0) {
                Xp.log(TAG + "trak not found in single video");
                return false;
            }

            byte[] trak1Data = new byte[moovIdx + moovSz - t1Idx];
            System.arraycopy(single, t1Idx, trak1Data, 0, trak1Data.length);
            ByteBuffer trak1Buf = ByteBuffer.wrap(trak1Data).order(ByteOrder.BIG_ENDIAN);

            // Update track_id from 1 to 2 in tkhd
            int tkhdI = findSubBox(trak1Data, "tkhd");
            if (tkhdI >= 0) {
                trak1Buf.putInt(tkhdI + 20, 2);
            }

            // Find stsc and stco in trak1
            int stscI = findSubBox(trak1Data, "stsc");
            int stcoI = findSubBox(trak1Data, "stco");
            if (stscI < 0 || stcoI < 0) {
                Xp.log(TAG + "stsc or stco not found in trak1");
                return false;
            }

            // Rebuild stsc: 1 entry (first_chunk=1, samples_per_chunk=1, desc_idx=1)
            byte[] newStsc = new byte[28];
            ByteBuffer.wrap(newStsc).order(ByteOrder.BIG_ENDIAN)
                    .putInt(28).put("stsc".getBytes())
                    .putInt(0).putInt(1)
                    .putInt(1).putInt(1).putInt(1);

            // Rebuild stco: 2 entries (offVideo0, offVideo1)
            byte[] newStco = new byte[24];
            ByteBuffer.wrap(newStco).order(ByteOrder.BIG_ENDIAN)
                    .putInt(24).put("stco".getBytes())
                    .putInt(0).putInt(2)
                    .putInt(offVideo0).putInt((rawS1 != null) ? offVideo1 : offVideo0);

            // Assemble new trak1 with new stsc and stco
            // Notice: stco in single was 20 bytes (1 chunk), new stco is 24 bytes (2 chunks) -> grows by 4
            ByteArrayOutputStream newTrak1Stream = new ByteArrayOutputStream();
            newTrak1Stream.write(trak1Data, 0, stscI);
            newTrak1Stream.write(newStsc);
            newTrak1Stream.write(trak1Data, stscI + 28, stcoI - (stscI + 28));
            newTrak1Stream.write(newStco);
            newTrak1Stream.write(trak1Data, stcoI + 20, trak1Data.length - (stcoI + 20));
            byte[] newTrak1 = newTrak1Stream.toByteArray();
            ByteBuffer newTrak1Buf = ByteBuffer.wrap(newTrak1).order(ByteOrder.BIG_ENDIAN);

            // Adjust container sizes in newTrak1 by +4
            for (String container : new String[]{"stbl", "minf", "mdia"}) {
                int ci = findSubBox(newTrak1, container);
                if (ci >= 0) {
                    newTrak1Buf.putInt(ci, newTrak1Buf.getInt(ci) + 4);
                }
            }
            newTrak1Buf.putInt(0, newTrak1.length); // update trak box size

            // 4. Update mvhd next_track_id to 3
            byte[] mvhdData = new byte[t1Idx - (moovIdx + 8)];
            System.arraycopy(single, moovIdx + 8, mvhdData, 0, mvhdData.length);
            ByteBuffer.wrap(mvhdData).order(ByteOrder.BIG_ENDIAN).putInt(104, 3);

            // 5. Assemble new moov
            ByteArrayOutputStream moovStream = new ByteArrayOutputStream();
            moovStream.write(mvhdData);
            moovStream.write(trak0);
            moovStream.write(newTrak1);
            byte[] newMoovPayload = moovStream.toByteArray();

            byte[] newMoovHeader = new byte[8];
            ByteBuffer.wrap(newMoovHeader).order(ByteOrder.BIG_ENDIAN)
                    .putInt(newMoovPayload.length + 8)
                    .put("moov".getBytes());

            // 6. Write final MP4
            File tempDest = new File(destFile.getAbsolutePath() + ".tmp");
            try (FileOutputStream fos = new FileOutputStream(tempDest)) {
                // Write ftyp + free (everything before mdat)
                fos.write(single, 0, mdatIdx);
                // Write new mdat
                fos.write(newMdatHeader);
                fos.write(newMdatPayload);
                // Write new moov
                fos.write(newMoovHeader);
                fos.write(newMoovPayload);
            }

            if (destFile.exists()) {
                destFile.delete();
            }
            boolean renamed = tempDest.renameTo(destFile);
            Xp.log(TAG + "injectGpmdTrack succeeded: " + destFile.getAbsolutePath()
                    + " (" + destFile.length() + "B)");
            return renamed;

        } catch (Throwable t) {
            Xp.log(TAG + "injectGpmdTrack failed: " + t);
            return false;
        }
    }

    private static int findBox(byte[] data, String tag) {
        byte[] tagBytes = tag.getBytes();
        for (int i = 0; i <= data.length - 8; i++) {
            if (data[i + 4] == tagBytes[0] && data[i + 5] == tagBytes[1]
                    && data[i + 6] == tagBytes[2] && data[i + 7] == tagBytes[3]) {
                return i;
            }
        }
        return -1;
    }

    private static int findSubBox(byte[] data, String tag) {
        byte[] tagBytes = tag.getBytes();
        for (int i = 0; i <= data.length - 8; i++) {
            if (data[i + 4] == tagBytes[0] && data[i + 5] == tagBytes[1]
                    && data[i + 6] == tagBytes[2] && data[i + 7] == tagBytes[3]) {
                return i;
            }
        }
        return -1;
    }
}
