package com.os4.musiccover;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;

/**
 * Pure Java Dual-Track MP4 Injector.
 * Takes a single-stream video MP4 (generated by Android's native MediaCodec + MediaMuxer)
 * and interleaves a 5-byte GoPro MET (gpmd) null-depth mask stream as Track 0.
 *
 * Uses precise MP4 box-tree traversal to locate boxes, supporting both stco and co64,
 * and arbitrary box orderings.
 */
public class FastMp4Muxer {

    private static final String TAG = "[MCDualMux] ";

    // 5-byte FastPlayer "empty/null mask" indicator (transparent foreground)
    private static final byte[] GPMD_NULL_MASK = new byte[] {
            (byte) 0x80, (byte) 0xb1, 0x71, (byte) 0x80, 0x00
    };

    // Base64 template of Track 0 (gpmd track) from Xiaomi's depth video (490 bytes)
    private static final String TRAK0_BASE64 =
            "AAAB6nRyYWsAAABcdGtoZAAAAAIAAAAAAAAAAAAAAAEAAAAAAAAAIgAAAAAAAAAAAAAAAgAAAAAAAQAA"
            + "AAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAACRlZHRzAAAAHGVsc3QAAAAA"
            + "AAAAAQAAACIAAAAAAAEAAAAAAWJtZGlhAAAAIG1kaGQAAAAAAAAAAAAAAAAAAV+QAAALuFXEAAAAAAAq"
            + "aGRscgAAAAAAAAAAbWV0YQAAAAAAAAAAAAAAAEdvUHJvIE1FVAAAAAEQbWluZgAAAFhnbWhkAAAAGGdt"
            + "aW4AAAAAAECAAIAAgAAAAAAAAAAALHRleHQAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAA"
            + "AAAAAAAMZ3BtZAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAACMc3RibAAA"
            + "ACRzdHNkAAAAAAAAAAEAAAAUZ3BtZAAAAAAAAAABAAAAAAAAABhzdHRzAAAAAAAAAAEAAAACAAAF3AAA"
            + "ABxzdHNjAAAAAAAAAAEAAAABAAAAAQAAAAEAAAAUc3RzegAAAAAAAAAFAAAAAgAAABhzdGNvAAAAAAAA"
            + "AAIAAAAsAAEQXA==";

    private static class Box {
        final String type;
        final int offset;
        final int size;

        Box(String type, int offset, int size) {
            this.type = type;
            this.offset = offset;
            this.size = size;
        }
    }

    private static List<Box> parseBoxes(byte[] data, int start, int end) {
        List<Box> list = new ArrayList<>();
        int pos = start;
        ByteBuffer buf = ByteBuffer.wrap(data).order(ByteOrder.BIG_ENDIAN);
        while (pos + 8 <= end) {
            int sz = buf.getInt(pos);
            String type = new String(data, pos + 4, 4, StandardCharsets.ISO_8859_1);
            long boxSz = (sz == 1 && pos + 16 <= end) ? buf.getLong(pos + 8) : (sz & 0xFFFFFFFFL);
            if (boxSz <= 0 || pos + boxSz > end) {
                boxSz = end - pos;
            }
            list.add(new Box(type, pos, (int) boxSz));
            pos += (int) boxSz;
        }
        return list;
    }

    private static Box findBox(List<Box> boxes, String type) {
        for (Box b : boxes) {
            if (b.type.equals(type)) return b;
        }
        return null;
    }

    /**
     * Converts a single-track video MP4 file into a dual-track (gpmd + video) MP4 file.
     *
     * @param singleTrackFile The source MP4 file produced by MediaMuxer
     * @param destFile        The target dual-track MP4 file for FastPlayer
     * @return true if successful, false otherwise
     */
    public static boolean injectGpmdTrack(File singleTrackFile, File destFile) {
        if (singleTrackFile == null || !singleTrackFile.exists() || singleTrackFile.length() < 64) {
            Xp.log(TAG + "singleTrackFile invalid: " + singleTrackFile);
            return false;
        }

        try {
            int fileLen = (int) singleTrackFile.length();
            byte[] single = new byte[fileLen];
            try (FileInputStream fis = new FileInputStream(singleTrackFile)) {
                int read = 0;
                while (read < fileLen) {
                    int r = fis.read(single, read, fileLen - read);
                    if (r < 0) break;
                    read += r;
                }
            }

            ByteBuffer buf = ByteBuffer.wrap(single).order(ByteOrder.BIG_ENDIAN);

            // Locate top-level boxes
            List<Box> top = parseBoxes(single, 0, fileLen);
            Box ftyp = findBox(top, "ftyp");
            Box mdat = findBox(top, "mdat");
            Box moov = findBox(top, "moov");
            if (ftyp == null || mdat == null || moov == null) {
                Xp.log(TAG + "missing essential top-level box (ftyp/mdat/moov)");
                return false;
            }

            // In moov: mvhd, trak
            List<Box> moovBoxes = parseBoxes(single, moov.offset + 8, moov.offset + moov.size);
            Box mvhd = findBox(moovBoxes, "mvhd");
            Box trak = findBox(moovBoxes, "trak");
            if (mvhd == null || trak == null) {
                Xp.log(TAG + "missing mvhd or trak in moov");
                return false;
            }

            // In trak: tkhd, mdia -> minf -> stbl
            List<Box> trakBoxes = parseBoxes(single, trak.offset + 8, trak.offset + trak.size);
            Box tkhd = findBox(trakBoxes, "tkhd");
            Box mdia = findBox(trakBoxes, "mdia");
            if (tkhd == null || mdia == null) {
                Xp.log(TAG + "missing tkhd or mdia in trak");
                return false;
            }

            List<Box> mdiaBoxes = parseBoxes(single, mdia.offset + 8, mdia.offset + mdia.size);
            Box minf = findBox(mdiaBoxes, "minf");
            if (minf == null) {
                Xp.log(TAG + "missing minf in mdia");
                return false;
            }

            List<Box> minfBoxes = parseBoxes(single, minf.offset + 8, minf.offset + minf.size);
            Box stbl = findBox(minfBoxes, "stbl");
            if (stbl == null) {
                Xp.log(TAG + "missing stbl in minf");
                return false;
            }

            List<Box> stblBoxes = parseBoxes(single, stbl.offset + 8, stbl.offset + stbl.size);
            Box stsc = findBox(stblBoxes, "stsc");
            Box stco = findBox(stblBoxes, "stco");
            Box co64 = findBox(stblBoxes, "co64");
            Box stsz = findBox(stblBoxes, "stsz");
            Box chunkBox = (stco != null) ? stco : co64;

            if (stsc == null || chunkBox == null || stsz == null) {
                Xp.log(TAG + "missing stsc, chunk offset (stco/co64), or stsz in stbl");
                return false;
            }

            // Read sample sizes from stsz
            int sampleCount = buf.getInt(stsz.offset + 16);
            if (sampleCount < 1) {
                Xp.log(TAG + "no samples found in stsz");
                return false;
            }

            int sample0Sz = buf.getInt(stsz.offset + 20);
            int sample1Sz = (sampleCount > 1) ? buf.getInt(stsz.offset + 24) : 0;

            // Read chunk offsets from chunkBox (stco / co64)
            int chunkCount = buf.getInt(chunkBox.offset + 12);
            long chunk0Offset;
            long chunk1Offset;
            if (chunkBox.type.equals("co64")) {
                chunk0Offset = buf.getLong(chunkBox.offset + 16);
                chunk1Offset = (chunkCount > 1) ? buf.getLong(chunkBox.offset + 24) : (chunk0Offset + sample0Sz);
            } else {
                chunk0Offset = buf.getInt(chunkBox.offset + 16) & 0xFFFFFFFFL;
                chunk1Offset = (chunkCount > 1) ? (buf.getInt(chunkBox.offset + 20) & 0xFFFFFFFFL) : (chunk0Offset + sample0Sz);
            }

            // Video sample bytes from single
            byte[] rawS0 = new byte[sample0Sz];
            System.arraycopy(single, (int) chunk0Offset, rawS0, 0, sample0Sz);

            byte[] rawS1 = null;
            if (sample1Sz > 0) {
                rawS1 = new byte[sample1Sz];
                System.arraycopy(single, (int) chunk1Offset, rawS1, 0, sample1Sz);
            }

            // 1. Build new mdat payload: interleave gpmd with video frames
            ByteArrayOutputStream newMdatStream = new ByteArrayOutputStream();
            int relOffGpmd0 = newMdatStream.size() + 8; // relative to mdat box start
            newMdatStream.write(GPMD_NULL_MASK);

            int relOffV0 = newMdatStream.size() + 8;
            newMdatStream.write(rawS0);

            int relOffGpmd1 = newMdatStream.size() + 8;
            newMdatStream.write(GPMD_NULL_MASK);

            int relOffV1 = newMdatStream.size() + 8;
            if (rawS1 != null) {
                newMdatStream.write(rawS1);
            } else {
                relOffV1 = relOffV0;
                relOffGpmd1 = relOffGpmd0;
            }

            byte[] newMdatPayload = newMdatStream.toByteArray();
            byte[] newMdatHeader = new byte[8];
            ByteBuffer.wrap(newMdatHeader).order(ByteOrder.BIG_ENDIAN)
                    .putInt(newMdatPayload.length + 8)
                    .put("mdat".getBytes(StandardCharsets.ISO_8859_1));

            // Absolute offsets in final MP4 (ftyp comes first)
            int absMdatStart = ftyp.size;
            int absOffGpmd0 = absMdatStart + relOffGpmd0;
            int absOffGpmd1 = absMdatStart + relOffGpmd1;
            int absOffV0 = absMdatStart + relOffV0;
            int absOffV1 = absMdatStart + relOffV1;

            // 2. Prepare trak0 from Base64 template
            byte[] trak0 = Base64.getDecoder().decode(TRAK0_BASE64);
            List<Box> t0Top = parseBoxes(trak0, 8, trak0.length);
            Box t0Mdia = findBox(t0Top, "mdia");
            Box t0Minf = findBox(parseBoxes(trak0, t0Mdia.offset + 8, t0Mdia.offset + t0Mdia.size), "minf");
            Box t0Stbl = findBox(parseBoxes(trak0, t0Minf.offset + 8, t0Minf.offset + t0Minf.size), "stbl");
            Box t0Stco = findBox(parseBoxes(trak0, t0Stbl.offset + 8, t0Stbl.offset + t0Stbl.size), "stco");
            if (t0Stco == null) {
                Xp.log(TAG + "stco not found in trak0 template");
                return false;
            }
            ByteBuffer.wrap(trak0).order(ByteOrder.BIG_ENDIAN)
                    .putInt(t0Stco.offset + 16, absOffGpmd0)
                    .putInt(t0Stco.offset + 20, absOffGpmd1);

            // 3. Prepare trak1 (video) from single
            byte[] trakData = new byte[trak.size];
            System.arraycopy(single, trak.offset, trakData, 0, trak.size);
            int trakRelOffset = trak.offset;

            // Update track_id to 2 in tkhd
            int relTkhd = tkhd.offset - trakRelOffset;
            ByteBuffer.wrap(trakData).order(ByteOrder.BIG_ENDIAN).putInt(relTkhd + 20, 2);

            // Rebuild stsc: 1 entry (first_chunk=1, samples_per_chunk=1, desc_idx=1)
            byte[] newStsc = new byte[28];
            ByteBuffer.wrap(newStsc).order(ByteOrder.BIG_ENDIAN)
                    .putInt(28).put("stsc".getBytes(StandardCharsets.ISO_8859_1))
                    .putInt(0).putInt(1)
                    .putInt(1).putInt(1).putInt(1);

            // Rebuild stco: 2 entries (absOffV0, absOffV1)
            byte[] newStco = new byte[24];
            ByteBuffer.wrap(newStco).order(ByteOrder.BIG_ENDIAN)
                    .putInt(24).put("stco".getBytes(StandardCharsets.ISO_8859_1))
                    .putInt(0).putInt(2)
                    .putInt(absOffV0).putInt(absOffV1);

            // Replace stsc and chunkBox in trakData
            int relStsc = stsc.offset - trakRelOffset;
            int relChunk = chunkBox.offset - trakRelOffset;

            ByteArrayOutputStream assembledTrak = new ByteArrayOutputStream();
            assembledTrak.write(trakData, 0, relStsc);
            assembledTrak.write(newStsc);
            assembledTrak.write(trakData, relStsc + stsc.size, relChunk - (relStsc + stsc.size));
            assembledTrak.write(newStco);
            assembledTrak.write(trakData, relChunk + chunkBox.size, trakData.length - (relChunk + chunkBox.size));
            byte[] newTrak1 = assembledTrak.toByteArray();
            ByteBuffer newTrak1Buf = ByteBuffer.wrap(newTrak1).order(ByteOrder.BIG_ENDIAN);

            // Size delta for trak1 and containers
            int sizeDelta = (newStsc.length - stsc.size) + (newStco.length - chunkBox.size);

            int relStbl = stbl.offset - trakRelOffset;
            int relMinf = minf.offset - trakRelOffset;
            int relMdia = mdia.offset - trakRelOffset;

            newTrak1Buf.putInt(relStbl, newTrak1Buf.getInt(relStbl) + sizeDelta);
            newTrak1Buf.putInt(relMinf, newTrak1Buf.getInt(relMinf) + sizeDelta);
            newTrak1Buf.putInt(relMdia, newTrak1Buf.getInt(relMdia) + sizeDelta);
            newTrak1Buf.putInt(0, newTrak1.length);

            // 4. Update mvhd next_track_id to 3
            byte[] mvhdData = new byte[mvhd.size];
            System.arraycopy(single, mvhd.offset, mvhdData, 0, mvhd.size);
            int mvhdVer = mvhdData[8] & 0xFF;
            int nextTrackOffset = (mvhdVer == 1) ? 116 : 104;
            ByteBuffer.wrap(mvhdData).order(ByteOrder.BIG_ENDIAN).putInt(nextTrackOffset, 3);

            // 5. Assemble moov
            ByteArrayOutputStream moovStream = new ByteArrayOutputStream();
            moovStream.write(mvhdData);
            moovStream.write(trak0);
            moovStream.write(newTrak1);
            byte[] newMoovPayload = moovStream.toByteArray();

            byte[] newMoovHeader = new byte[8];
            ByteBuffer.wrap(newMoovHeader).order(ByteOrder.BIG_ENDIAN)
                    .putInt(newMoovPayload.length + 8)
                    .put("moov".getBytes(StandardCharsets.ISO_8859_1));

            // 6. Write final MP4: [ftyp][new mdat][new moov]
            byte[] ftypData = new byte[ftyp.size];
            System.arraycopy(single, ftyp.offset, ftypData, 0, ftyp.size);

            File tempDest = new File(destFile.getAbsolutePath() + ".tmp");
            try (FileOutputStream fos = new FileOutputStream(tempDest)) {
                fos.write(ftypData);
                fos.write(newMdatHeader);
                fos.write(newMdatPayload);
                fos.write(newMoovHeader);
                fos.write(newMoovPayload);
            }

            if (destFile.exists()) {
                destFile.delete();
            }
            boolean renamed = tempDest.renameTo(destFile);
            Xp.log(TAG + "injectGpmdTrack succeeded: " + destFile.getAbsolutePath()
                    + " (" + destFile.length() + "B, delta=" + sizeDelta + ")");
            return renamed;

        } catch (Throwable t) {
            Xp.log(TAG + "injectGpmdTrack failed: " + t);
            return false;
        }
    }
}
